INSERT IGNORE INTO plan_templates (id, code, title, description, source_type) VALUES
(1, 'HTML_8_WEEK_PLAN', '八周系统进阶作战图', '从 study_plan.html 迁移的主线计划、实践任务和学校三科。', 'HTML');

INSERT IGNORE INTO plan_template_tasks (template_id, week_no, section_title, title, description, task_type, sort_order) VALUES
(1, 1, 'Linux 基础', '熟练 ls / cd / grep / find / ps / kill / chmod / chown', NULL, 'MAIN_PLAN', 101),
(1, 1, 'Linux 基础', '理解 shell 重定向 (>, >>, 2>&1) 与管道 |', NULL, 'MAIN_PLAN', 102),
(1, 1, 'Linux 基础', '看懂进程相关命令：top / htop / pstree / lsof', NULL, 'MAIN_PLAN', 103),
(1, 1, 'C++ 编译链', '搞清 g++ 选项：-O0/-O2 -g -Wall -std=c++17', NULL, 'MAIN_PLAN', 104),
(1, 1, 'C++ 编译链', '手画一遍：预处理 -> 编译 -> 汇编 -> 链接 四阶段', NULL, 'MAIN_PLAN', 105),
(1, 1, 'C++ 编译链', '静态库 .a 与动态库 .so 的制作与链接顺序坑', NULL, 'MAIN_PLAN', 106),
(1, 1, 'C++ 编译链', 'gdb 基本用法：break / run / next / print / bt', NULL, 'MAIN_PLAN', 107),
(1, 1, 'C++ 编译链', 'valgrind 检测内存泄漏', NULL, 'MAIN_PLAN', 108),
(1, 1, '本周实践', '不用 IDE，纯命令行写一个含 2-3 个源文件的小项目，手写 g++ 命令完成编译并运行。', NULL, 'MAIN_PLAN', 109),
(1, 2, 'Git 工作流', '理解三区：工作区 / 暂存区 / 版本库', NULL, 'MAIN_PLAN', 201),
(1, 2, 'Git 工作流', 'commit / branch / checkout / merge / rebase 区别', NULL, 'MAIN_PLAN', 202),
(1, 2, 'Git 工作流', 'remote / push / pull / fetch / cherry-pick', NULL, 'MAIN_PLAN', 203),
(1, 2, 'Git 工作流', '处理冲突 + .gitignore + git log --graph --oneline', NULL, 'MAIN_PLAN', 204),
(1, 2, 'Git 工作流', '注册 GitHub，把已有项目推上去', NULL, 'MAIN_PLAN', 205),
(1, 2, 'CMake 入门', 'add_executable / target_link_libraries / target_include_directories', NULL, 'MAIN_PLAN', 206),
(1, 2, 'CMake 入门', 'add_subdirectory 组织多目录工程', NULL, 'MAIN_PLAN', 207),
(1, 2, 'CMake 入门', 'find_package 链接 FFmpeg / Qt', NULL, 'MAIN_PLAN', 208),
(1, 2, 'CMake 入门', '区分 PUBLIC / PRIVATE / INTERFACE', NULL, 'MAIN_PLAN', 209),
(1, 2, 'CMake 入门', 'Debug / Release 构建类型与命令行变量传参', NULL, 'MAIN_PLAN', 210),
(1, 2, '本周实践', '把上周的项目改造成 CMake 工程：root CMakeLists + 子模块，build 目录构建，再 push 到 GitHub。', NULL, 'MAIN_PLAN', 211),
(1, 3, '基础概念', '进程 vs 线程 vs 协程 区别和适用场景', NULL, 'MAIN_PLAN', 301),
(1, 3, '基础概念', 'std::thread 创建、传参、join / detach', NULL, 'MAIN_PLAN', 302),
(1, 3, '基础概念', 'std::mutex + std::lock_guard / std::unique_lock', NULL, 'MAIN_PLAN', 303),
(1, 3, '基础概念', '死锁四条件 + std::scoped_lock 多锁同时获取', NULL, 'MAIN_PLAN', 304),
(1, 3, '基础概念', 'std::condition_variable 与 wait / notify 用法', NULL, 'MAIN_PLAN', 305),
(1, 3, '本周实践', '实现一个线程安全阻塞队列（push / pop），写两个生产者两个消费者跑通。', NULL, 'MAIN_PLAN', 306),
(1, 4, '高阶机制', 'std::atomic 与 memory_order 六种语义', NULL, 'MAIN_PLAN', 401),
(1, 4, '高阶机制', '理解 CAS（compare_exchange）思想', NULL, 'MAIN_PLAN', 402),
(1, 4, '高阶机制', 'std::future / std::promise / std::async / packaged_task', NULL, 'MAIN_PLAN', 403),
(1, 4, '高阶机制', '读写锁 std::shared_mutex', NULL, 'MAIN_PLAN', 404),
(1, 4, '高阶机制', '线程池设计要点：任务队列、worker 数量、停机', NULL, 'MAIN_PLAN', 405),
(1, 4, '本周实践', '从零实现一个固定大小线程池，submit 接口返回 future，跑一组耗时任务对比单线程性能。', NULL, 'MAIN_PLAN', 406),
(1, 5, '协议与模型', 'OSI 七层 vs TCP/IP 四层 模型对照', NULL, 'MAIN_PLAN', 501),
(1, 5, '协议与模型', 'TCP 三次握手 / 四次挥手 / 11 种状态', NULL, 'MAIN_PLAN', 502),
(1, 5, '协议与模型', 'UDP vs TCP 适用场景对比', NULL, 'MAIN_PLAN', 503),
(1, 5, '协议与模型', '字节序 htons / htonl / ntohs / ntohl', NULL, 'MAIN_PLAN', 504),
(1, 5, 'BSD Socket API', 'socket / bind / listen / accept / connect 调用顺序', NULL, 'MAIN_PLAN', 505),
(1, 5, 'BSD Socket API', 'send / recv 与阻塞 / 非阻塞模式', NULL, 'MAIN_PLAN', 506),
(1, 5, 'BSD Socket API', 'errno + perror 排查 socket 错误', NULL, 'MAIN_PLAN', 507),
(1, 5, 'BSD Socket API', '用 Wireshark 抓自己写的 TCP 包看看', NULL, 'MAIN_PLAN', 508),
(1, 5, '本周实践', '写一个 TCP echo server + client，能并发支持多个 client（每连接一个线程版本即可）。', NULL, 'MAIN_PLAN', 509),
(1, 6, '多路复用模型', 'select / poll / epoll 的差异与代价', NULL, 'MAIN_PLAN', 601),
(1, 6, '多路复用模型', 'epoll LT 与 ET 触发模式', NULL, 'MAIN_PLAN', 602),
(1, 6, '多路复用模型', 'Reactor 模式核心思想', NULL, 'MAIN_PLAN', 603),
(1, 6, '多路复用模型', 'EAGAIN / EWOULDBLOCK 的处理', NULL, 'MAIN_PLAN', 604),
(1, 6, '多路复用模型', '手撕一遍简单 HTTP/1.1 报文解析', NULL, 'MAIN_PLAN', 605),
(1, 6, '本周实践', '基于 epoll 写一个非阻塞 echo 服务器，能稳定撑住 1000+ 并发连接，用 ab 或自己写脚本压测。', NULL, 'MAIN_PLAN', 606),
(1, 7, '解复用 demux', 'AVFormatContext / AVStream / AVPacket 三者关系', NULL, 'MAIN_PLAN', 701),
(1, 7, '解复用 demux', 'avformat_open_input + avformat_find_stream_info', NULL, 'MAIN_PLAN', 702),
(1, 7, '解复用 demux', 'av_read_frame 取包，区分音视频流', NULL, 'MAIN_PLAN', 703),
(1, 7, '解复用 demux', '理解 time_base / PTS / DTS 三者关系', NULL, 'MAIN_PLAN', 704),
(1, 7, '复用 mux', 'avformat_alloc_output_context2', NULL, 'MAIN_PLAN', 705),
(1, 7, '复用 mux', 'avcodec_parameters_copy 复制流参数', NULL, 'MAIN_PLAN', 706),
(1, 7, '复用 mux', 'avformat_write_header / av_interleaved_write_frame / av_write_trailer', NULL, 'MAIN_PLAN', 707),
(1, 7, '复用 mux', 'av_rescale_q 换算时间基', NULL, 'MAIN_PLAN', 708),
(1, 7, '复用 mux', '收尾流程：avio_closep + avformat_free_context', NULL, 'MAIN_PLAN', 709),
(1, 7, '本周实践', '写一个 remux 工具：mp4 -> flv（或 mp4 -> ts），不重新编码，保留原音视频流。', NULL, 'MAIN_PLAN', 710),
(1, 8, '二选一综合项目', '方向 A：多线程 TCP 文件服务器（并发上传/下载，断点续传可选）', NULL, 'MAIN_PLAN', 801),
(1, 8, '二选一综合项目', '方向 B：基于 FFmpeg 的 HTTP 推拉流小工具', NULL, 'MAIN_PLAN', 802),
(1, 8, '二选一综合项目', '用 CMake 组织 + Git 管理 + 写 README', NULL, 'MAIN_PLAN', 803),
(1, 8, '二选一综合项目', '产出一份简短设计文档（架构图 + 关键决策）', NULL, 'MAIN_PLAN', 804),
(1, 8, '两个月复盘', '回顾每周笔记，挑出 3 个最大盲点重新过一遍', NULL, 'MAIN_PLAN', 805),
(1, 8, '两个月复盘', '面试题角度自测：并发 / 网络 / FFmpeg 各 5 题', NULL, 'MAIN_PLAN', 806),
(1, 8, '两个月复盘', '更新简历 / GitHub 主页项目说明', NULL, 'MAIN_PLAN', 807),
(1, 8, '本周实践', '把本周项目录屏 5 分钟讲清楚整个架构，讲不清就是没真懂。', NULL, 'MAIN_PLAN', 808),
(1, 0, '操作系统', '进程 / 线程 / 调度算法（FCFS、SJF、优先级、多级反馈队列）', NULL, 'SCHOOL_COURSE', 901),
(1, 0, '操作系统', '内存管理：分页、分段、虚拟内存、缺页处理', NULL, 'SCHOOL_COURSE', 902),
(1, 0, '操作系统', '文件系统：inode、VFS、磁盘块分配', NULL, 'SCHOOL_COURSE', 903),
(1, 0, '操作系统', 'I/O 子系统与设备驱动框架', NULL, 'SCHOOL_COURSE', 904),
(1, 0, '计算机组成原理', '数据表示：原 / 反 / 补码、IEEE 754 浮点', NULL, 'SCHOOL_COURSE', 905),
(1, 0, '计算机组成原理', 'CPU：指令周期、流水线、冒险与转发', NULL, 'SCHOOL_COURSE', 906),
(1, 0, '计算机组成原理', '存储层次：cache 映射、写策略、TLB', NULL, 'SCHOOL_COURSE', 907),
(1, 0, '计算机组成原理', '总线 & I/O：DMA、中断', NULL, 'SCHOOL_COURSE', 908),
(1, 0, '数据库', '关系模型 + 范式 1NF / 2NF / 3NF / BCNF', NULL, 'SCHOOL_COURSE', 909),
(1, 0, '数据库', 'SQL：JOIN、子查询、聚合、窗口函数', NULL, 'SCHOOL_COURSE', 910),
(1, 0, '数据库', '事务 ACID + 四种隔离级别 + MVCC', NULL, 'SCHOOL_COURSE', 911),
(1, 0, '数据库', '索引：B+ 树、哈希；最左前缀 / 回表概念', NULL, 'SCHOOL_COURSE', 912);

INSERT IGNORE INTO goal_templates (id, code, title, description, category, priority, source_type, recommended_order) VALUES
(1, 'AV_CLIENT_SDK', '客户端播放器 / 音视频 SDK 求职主线', '最契合 C++ 与 FFmpeg 基础：播放器内核、SDK 集成、音视频同步、跨平台渲染和性能优化。', '客户端播放器/SDK', 'HIGH', 'PDF_GUIDE', 1),
(2, 'STREAMING_SERVER', '流媒体服务端 / 直播推流求职主线', '以 Go/Java 服务端能力为主，辅以 C++、FFmpeg、RTMP/HLS/SRS/ZLMediaKit 和工程化部署。', '流媒体服务端', 'HIGH', 'PDF_GUIDE', 2),
(3, 'RTC_WEBRTC', 'RTC / WebRTC 实时通信扩展路线', '适合作为进阶路线：WebRTC、RTP/RTCP、弱网传输、SFU、客户端 SDK 集成。算法岗谨慎投入。', 'RTC/WebRTC', 'MEDIUM', 'PDF_GUIDE', 3);

INSERT IGNORE INTO goal_template_stages (template_id, title, description, stage_order) VALUES
(1, '补强 C++17 与并发基础', '智能指针、RAII、STL、线程同步、生产者消费者队列。', 1),
(1, '完成 FFmpeg 网络流与 remux', '掌握 avformat、time_base、PTS/DTS、拉流与转封装。', 2),
(1, '播放器最小闭环', '完成解复用、解码、音视频同步、基础渲染或日志可视化。', 3),
(1, '阅读播放器开源项目', '阅读 ijkplayer、mpv、VLC 或 FFmpeg 示例模块并写笔记。', 4),
(1, '准备实习作品集', '整理 GitHub README、演示视频、面试复盘和问题库。', 5),
(2, 'Go/Java 服务端基础', '补充 Web API、并发、MySQL、Redis、消息队列基础。', 1),
(2, '直播协议和组件实验', '本地搭 SRS，用 OBS 推 RTMP，FFmpeg 拉流转 HLS。', 2),
(2, '读 SRS / ZLMediaKit 核心模块', '关注连接管理、协程/线程模型、协议解析。', 3),
(2, '实现简版流媒体服务', '完成 RTMP metadata 解析或 HTTP-FLV 拉流服务。', 4),
(2, '投递准备', '补八股、算法、项目压测和部署文档。', 5),
(3, 'WebRTC 协议入门', 'SDP、ICE、STUN、TURN、RTP、RTCP 的端到端流程。', 1),
(3, '跑通 1v1 Demo', '搭建 WebRTC 1v1 demo，记录信令和媒体链路。', 2),
(3, '编译或阅读 Native WebRTC', '跑 peerconnection_client 或阅读关键模块。', 3),
(3, '搭建简易 SFU', '用 mediasoup、Pion 或 SRS WebRTC 做小型多人通话。', 4),
(3, 'SDK 集成方向面试准备', '聚焦 C++、网络、客户端集成和弱网问题。', 5);
